# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "opencosmo" %}
{% set version = "0.7.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  noarch: python
  skip: true #[win]
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python>={{ python_min }}
    - numpy>=1.26
    - h5py 
    - pydantic
    - healpy
    - hdf5plugin
    - astropy>=7.0.1,<8.0.0
    - deprecated


test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ArgonneCPAC/OpenCosmo
  summary: 'The OpenCosmo Python Toolkit' 
  description: |
    The OpenCosmo Python Toolkit provides utilities for reading, writing and manipulating data from cosmological simulations produced by the Cosmolgical Physics and Advanced Computing (CPAC) group at Argonne National Laboratory. The OpenCosmo toolkit integrates with standard tools such as AstroPy, and allows you to manipulate data in a fully-consistent cosmological context.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  doc_url: https://opencosmo.readthedocs.org/

extra:
  recipe-maintainers:
    - AstroPatty
